apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-scaffolder-backend-module-utils
  namespace: rhdh
  title: "Scaffolder Backend Module Utils"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-utils
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-utils
  tags:
    - software-templates
spec:
  packageName: "@roadiehq/scaffolder-backend-module-utils"
  # Tag: bs_1.54.6__4.1.2
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/roadiehq-scaffolder-backend-module-utils@sha256:6d564dd4f7e699d6d7652d8a7c93f178b22736515035af2e54c56175fab98c21"
  version: 4.1.2
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Roadie
  support: community
  lifecycle: active
  partOf:
    - roadie-scaffolder-util-actions
  appConfigNotRequired: true
  appConfigExamples: []
